version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    reviewers:
      - beelzer
    labels:
      - dependencies
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: 'chore'
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - beelzer
    labels:
      - ci
    commit-message:
      prefix: 'ci'
      include: scope
